// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261007190341_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Data.Ban", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ByPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("by_player_id");

                    b.Property<int>("ChampionId")
                        .HasColumnType("integer")
                        .HasColumnName("champion_id");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid>("TargetPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_player_id");

                    b.HasKey("Id")
                        .HasName("pk_ban");

                    b.HasIndex("SeriesId", "ByPlayerId", "ChampionId")
                        .IsUnique()
                        .HasDatabaseName("ix_ban_series_id_by_player_id_champion_id");

                    b.ToTable("ban", (string)null);
                });

            modelBuilder.Entity("Api.Data.DeckChampion", b =>
                {
                    b.Property<Guid>("SeriesPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_player_id");

                    b.Property<int>("ChampionId")
                        .HasColumnType("integer")
                        .HasColumnName("champion_id");

                    b.Property<bool>("Banned")
                        .HasColumnType("boolean")
                        .HasColumnName("banned");

                    b.Property<Guid?>("ConsumedInRoundId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumed_in_round_id");

                    b.HasKey("SeriesPlayerId", "ChampionId")
                        .HasName("pk_deck_champion");

                    b.ToTable("deck_champion", (string)null);
                });

            modelBuilder.Entity("Api.Data.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_user_id");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_user_id");

                    b.HasKey("Id")
                        .HasName("pk_invitation");

                    b.HasIndex("FromUserId")
                        .HasDatabaseName("ix_invitation_from_user_id");

                    b.HasIndex("ToUserId", "Status")
                        .HasDatabaseName("ix_invitation_to_user_id_status");

                    b.ToTable("invitation", (string)null);
                });

            modelBuilder.Entity("Api.Data.Observation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_id");

                    b.Property<double>("EventTime")
                        .HasColumnType("double precision")
                        .HasColumnName("event_time");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<Guid>("ReportedByPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reported_by_player_id");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid")
                        .HasColumnName("round_id");

                    b.Property<Guid?>("SubjectPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_player_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<int?>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_observation");

                    b.HasIndex("RoundId", "ReportedByPlayerId", "Type", "EventId")
                        .IsUnique()
                        .HasDatabaseName("ix_observation_round_id_reported_by_player_id_type_event_id");

                    b.ToTable("observation", (string)null);
                });

            modelBuilder.Entity("Api.Data.RiotAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("game_name");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at");

                    b.Property<string>("Puuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("puuid");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("RiotIdNormalized")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("riot_id_normalized");

                    b.Property<string>("TagLine")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tag_line");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_riot_account");

                    b.HasIndex("Puuid")
                        .IsUnique()
                        .HasDatabaseName("ix_riot_account_puuid");

                    b.HasIndex("RiotIdNormalized")
                        .HasDatabaseName("ix_riot_account_riot_id_normalized");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_riot_account_user_id");

                    b.ToTable("riot_account", (string)null);
                });

            modelBuilder.Entity("Api.Data.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisputeVoteA")
                        .HasColumnType("text")
                        .HasColumnName("dispute_vote_a");

                    b.Property<string>("DisputeVoteB")
                        .HasColumnType("text")
                        .HasColumnName("dispute_vote_b");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<long?>("LolGameId")
                        .HasColumnType("bigint")
                        .HasColumnName("lol_game_id");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("VoidReason")
                        .HasColumnType("text")
                        .HasColumnName("void_reason");

                    b.Property<Guid?>("VoidRequestedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("void_requested_by");

                    b.Property<Guid?>("WinnerPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("winner_player_id");

                    b.Property<string>("WinningCondition")
                        .HasColumnType("jsonb")
                        .HasColumnName("winning_condition");

                    b.HasKey("Id")
                        .HasName("pk_round");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_round_status");

                    b.HasIndex("SeriesId", "Number", "Attempt")
                        .IsUnique()
                        .HasDatabaseName("ix_round_series_id_number_attempt");

                    b.ToTable("round", (string)null);
                });

            modelBuilder.Entity("Api.Data.RoundAssignment", b =>
                {
                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid")
                        .HasColumnName("round_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int?>("ChampionId")
                        .HasColumnType("integer")
                        .HasColumnName("champion_id");

                    b.Property<bool>("GameStartedReported")
                        .HasColumnType("boolean")
                        .HasColumnName("game_started_reported");

                    b.Property<int?>("ReportedChampionId")
                        .HasColumnType("integer")
                        .HasColumnName("reported_champion_id");

                    b.Property<bool>("ReportedLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("reported_locked");

                    b.Property<int?>("ReportedSpell1Id")
                        .HasColumnType("integer")
                        .HasColumnName("reported_spell1id");

                    b.Property<int?>("ReportedSpell2Id")
                        .HasColumnType("integer")
                        .HasColumnName("reported_spell2id");

                    b.Property<DateTimeOffset?>("RevealedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revealed_at");

                    b.Property<int?>("Spell1Id")
                        .HasColumnType("integer")
                        .HasColumnName("spell1id");

                    b.Property<int?>("Spell2Id")
                        .HasColumnType("integer")
                        .HasColumnName("spell2id");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.HasKey("RoundId", "PlayerId")
                        .HasName("pk_round_assignment");

                    b.ToTable("round_assignment", (string)null);
                });

            modelBuilder.Entity("Api.Data.Series", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BestOf")
                        .HasColumnType("integer")
                        .HasColumnName("best_of");

                    b.Property<string>("ChampionMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("champion_mode");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DrawSeed")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("draw_seed");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("SpellMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("spell_mode");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("WinExpression")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("win_expression");

                    b.Property<Guid?>("WinnerPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("winner_player_id");

                    b.HasKey("Id")
                        .HasName("pk_series");

                    b.ToTable("series", null, t =>
                        {
                            t.HasCheckConstraint("ck_series_best_of", "best_of IN (1,3,5,7,9,11)");
                        });
                });

            modelBuilder.Entity("Api.Data.SeriesPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DeckLockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deck_locked_at");

                    b.Property<string>("PoolSnapshot")
                        .HasColumnType("jsonb")
                        .HasColumnName("pool_snapshot");

                    b.Property<DateTimeOffset?>("PoolUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pool_updated_at");

                    b.Property<Guid>("RiotAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("riot_account_id");

                    b.Property<int>("RoundsWon")
                        .HasColumnType("integer")
                        .HasColumnName("rounds_won");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("slot");

                    b.Property<DateTimeOffset?>("SpellBudgetLockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("spell_budget_locked_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_series_player");

                    b.HasIndex("RiotAccountId")
                        .HasDatabaseName("ix_series_player_riot_account_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_series_player_user_id");

                    b.HasIndex("SeriesId", "Slot")
                        .IsUnique()
                        .HasDatabaseName("ix_series_player_series_id_slot");

                    b.ToTable("series_player", (string)null);
                });

            modelBuilder.Entity("Api.Data.SpellToken", b =>
                {
                    b.Property<Guid>("SeriesPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_player_id");

                    b.Property<int>("SpellId")
                        .HasColumnType("integer")
                        .HasColumnName("spell_id");

                    b.Property<int>("QuantityInitial")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_initial");

                    b.Property<int>("QuantityLeft")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_left");

                    b.HasKey("SeriesPlayerId", "SpellId")
                        .HasName("pk_spell_token");

                    b.ToTable("spell_token", (string)null);
                });

            modelBuilder.Entity("Api.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_email");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Api.Data.Ban", b =>
                {
                    b.HasOne("Api.Data.Series", null)
                        .WithMany("Bans")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ban_series_series_id");
                });

            modelBuilder.Entity("Api.Data.DeckChampion", b =>
                {
                    b.HasOne("Api.Data.SeriesPlayer", null)
                        .WithMany("Deck")
                        .HasForeignKey("SeriesPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deck_champion_series_player_series_player_id");
                });

            modelBuilder.Entity("Api.Data.Invitation", b =>
                {
                    b.HasOne("Api.Data.User", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invitation_user_from_user_id");

                    b.HasOne("Api.Data.User", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invitation_user_to_user_id");

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("Api.Data.Observation", b =>
                {
                    b.HasOne("Api.Data.Round", null)
                        .WithMany("Observations")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_observation_round_round_id");
                });

            modelBuilder.Entity("Api.Data.RiotAccount", b =>
                {
                    b.HasOne("Api.Data.User", "User")
                        .WithOne("RiotAccount")
                        .HasForeignKey("Api.Data.RiotAccount", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_riot_account_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Data.Round", b =>
                {
                    b.HasOne("Api.Data.Series", "Series")
                        .WithMany("Rounds")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_round_series_series_id");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Api.Data.RoundAssignment", b =>
                {
                    b.HasOne("Api.Data.Round", null)
                        .WithMany("Assignments")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_round_assignment_round_round_id");
                });

            modelBuilder.Entity("Api.Data.SeriesPlayer", b =>
                {
                    b.HasOne("Api.Data.RiotAccount", "RiotAccount")
                        .WithMany()
                        .HasForeignKey("RiotAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_series_player_riot_account_riot_account_id");

                    b.HasOne("Api.Data.Series", "Series")
                        .WithMany("Players")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_series_player_series_series_id");

                    b.HasOne("Api.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_series_player_user_user_id");

                    b.Navigation("RiotAccount");

                    b.Navigation("Series");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Data.SpellToken", b =>
                {
                    b.HasOne("Api.Data.SeriesPlayer", null)
                        .WithMany("SpellTokens")
                        .HasForeignKey("SeriesPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spell_token_series_player_series_player_id");
                });

            modelBuilder.Entity("Api.Data.Round", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Observations");
                });

            modelBuilder.Entity("Api.Data.Series", b =>
                {
                    b.Navigation("Bans");

                    b.Navigation("Players");

                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("Api.Data.SeriesPlayer", b =>
                {
                    b.Navigation("Deck");

                    b.Navigation("SpellTokens");
                });

            modelBuilder.Entity("Api.Data.User", b =>
                {
                    b.Navigation("RiotAccount");
                });
#pragma warning restore 612, 618
        }
    }
}
